# Generated by Django 5.0.1 on 2024-02-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_object',
            new_name='user_objects',
        ),
    ]
